""" {{cookiecutter.project_name}} """
__author__ = "{{cookiecutter.person_or_organization_name}}"
__version__ = "0.0.1"
__title__ = "{{cookiecutter.project_name}}"
__license__ = "{{cookiecutter.license}}"
