#!/usr/bin/env bash

grep "^bindsym" ~/.config/i3/config \
    | sed 's/-\(-\w\+\)\+//g;s/$mod/Win/g;s/Mod1/Alt/g;s/exec //;s/bindsym //;s/^\s\+//;s/^\([^ ]\+\) \(.\+\)$/\2: \1/;s/^\s\+//' \
    | tr -s ' ' \
    | rofi -dmenu -l 20
