#!/usr/bin/env bash

set -e

echo 'Install gimp and some plugins'
sudo apt-get install \
  gimp \
  gimp-data-extras \
  gimp-gap \
  gimp-gmic \
  gimp-lensfun \
  gimp-texturize \
  libgimp2.0-dev \


echo 'Install icc color profiles...'
sudo apt-get install icc-profiles-free

echo 'Clone the resynthesizer repo, compile, and install...'
mkdir -p /tmp/gimplug/resynthesizer
cd /tmp/gimplug/resynthesizer
git clone https://github.com/bootchk/resynthesizer.git . || git pull
./autogen.sh
./configure
make
echo 'sudo make install resynthesizer...'
sudo make install


echo 'Download Heal selection fix script directly from gimp plugin registry...'
cd ~/.gimp-2.8/
wget -O scripts/smart-remove-fix.scm http://registry.gimp.org/files/smart-remove.scm
echo 'Change the meta name of the fixed heal selection script to distinguish from orig...'
sed -i scripts/smart-remove-fix.scm 's?"<Image>/Filters/Enhance/Heal selection..."?"<Image>/Filters/Enhance/Heal selection (fix)..."?'

echo "Clone 'export layer' plugin from github and install..."
mkdir -p /tmp/gimp-export-layers
git clone https://github.com/khalim19/gimp-plugin-export-layers.git /tmp/gimp-export-layers
cd /tmp/gimp-export-layers
cp -r export_layers export_layers.py pygimplib ~/.gimp-2.8/plug-ins/
cd ~/.gimp-2.8/
rm -rf /tmp/gimp-export-layers
