#!/usr/bin/env bash

set -e

###
# Install
###
# Normal packages
echo "::::Install tools and applets upon which the i3 config will rely..."
sudo apt-get install \
  blueman \
  dmenu \
  fonts-font-awesome \
  gsimplecal \
  i3blocks \
  i3lock \
  lastpass-cli \
  libimage-exiftool-perl \
  pasystray \
  pavucontrol \
  pcmanfm-qt \
  shutter \
  terminator \
  ubuntu-restricted-extras \
  vim-gtk3 \

## Other
# Vim-anywhere
git clone https://github.com/cknadler/vim-anywhere.git "${HOME}/.bin/vim-anywhere"

# i3ipc
echo '::::Pip install the i3ipc module for this user...'
pip3 install --user --upgrade i3ipc
echo '::::Download focus-next-visible.py from the i3ipc-python github repo...'
wget -O ~/.config/i3/focus-next-visible.py https://raw.githubusercontent.com/acrisci/i3ipc-python/master/examples/focus-next-visible.py
ls -l ~/.config/i3/focus-next-visible.py

# uniemoji
git clone https://github.com/salty-horse/ibus-uniemoji /tmp/uniemoji
cd /tmp/uniemoji
sudo make install
ibus restart


###
# Config
###
# dunst
echo "::::Replace notify-osd with dunst..."
sudo apt-get remove notify-osd
sudo killall notify-osd || true
sudo apt-get install dunst
notify-send "dunst test" "Are we dunst yet?"

# x resources enable precompilation options on boot
echo '::::Alter gdm3 default Xsession to NOT skip over prepocessor directives...'
sudo sed -i 's/-nocpp //g' /etc/gdm3/Xsession
echo '::::Merge in Xresources now...'
xrdb -merge ~/.Xresources
