#!/usr/bin/env bash

echo 'Install a bunch of basic packages...'
sudo apt-get install \
  curl \
  gnuplot-x11 \
  htop \
  jq \
  libgimp2.0-dev \
  links \
  moreutils \
  mosh \
  pandoc \
  ranger \
  screen \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  tmux \
  vim \
  w3m \
  x11-utils \
  xclip \
  units \


# echo 'Install some basic packages from pip...'
# pip install \

# echo 'Install some basic Go packages...'
# go get \

# echo 'Install odd scripts...'
wget -O "${HOME}/.bin/tmux-cssh" https://raw.githubusercontent.com/peikk0/tmux-cssh/master/tmux-cssh
chmod +x "${HOME}/.bin/tmux-cssh"
