#!/usr/bin/env bash

echo 'Install a bunch of basic packages...'
sudo apt-get install \
  curl \
  gnuplot-x11 \
  htop \
  jmtpfs \
  jq \
  libgimp2.0-dev \
  links \
  moreutils \
  mosh \
  pandoc \
  python3-pip \
  ranger \
  screen \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  translate-shell \
  units \
  vim \
  w3m \
  wkhtmltopdf \
  x11-utils \
  xclip \


# echo 'Install some basic packages from pip...'
pip install \
  cookiecutter \


# echo 'Install some basic Go packages...'
# go get \

# echo 'Install odd scripts...'
wget -O "${HOME}/.bin/tmux-cssh" https://raw.githubusercontent.com/peikk0/tmux-cssh/master/tmux-cssh
chmod +x "${HOME}/.bin/tmux-cssh"
