#!/usr/bin/env bash

set -e

echo 'Install ppa, gimp, and some plugins'
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get install \
  gimp \
  gimp-data-extras \
  gimp-gap \
  gimp-gmic \
  gimp-lensfun \
  gimp-texturize \
  libgimp2.0-dev \


echo 'Install icc color profiles...'
sudo apt-get install icc-profiles-free

echo "Clone 'export layer' plugin from github and install..."
plugin_tmp="$(mktemp -d)"
export_layers_tmp="${plugin_tmp}/gimp-export-layers"
mkdir -p "${plugin_tmp}/${export_layers_tmp}"
git clone https://github.com/khalim19/gimp-plugin-export-layers.git "${export_layers_tmp}"
cp -r "${export_layers_tmp}/"{export_layers,export_layers.py} "${XDG_CONFIG_HOME:-${HOME}/.config}/GIMP/2.10/plug-ins/"


echo "Temporary files left in '${plugin_tmp}'"
