#!/usr/bin/env bash

set -e

###
# Repos
###
sudo add-apt-repository ppa:peek-developers/stable
sudo apt-get update

###
# Install
###
# Normal packages
echo '::::Install tools and applets upon which the i3 config will rely...'
sudo apt-get install \
  adwaita-icon-theme-full \
  blueman \
  dmenu \
  fonts-font-awesome \
  gsimplecal \
  i3blocks \
  i3lock \
  lastpass-cli \
  libimage-exiftool-perl \
  pasystray \
  pavucontrol \
  pcmanfm-qt \
  peek \
  rofi \
  shutter \
  terminator \
  ubuntu-restricted-extras \
  vim-gtk3 \
  xautolock \

## Other
echo '::::Install from misc...'

echo 'Install tomaatti pomodoro timer for i3...'
pip3 install tomaatti

# Vim-
if [ ! -d "${HOME}/.bin/vim-anywhere" ]; then
  git clone https://github.com/cspeterson/vim-anywhere.git "${HOME}/.bin/vim-anywhere"
else
  git -C "${HOME}/.bin/vim-anywhere" pull
fi

# emoji input via my splatmoji script
# https://github.com/cspeterson/splatmoji
echo '::::Install/update splatmoji...'
if [ ! -d "${HOME}/.bin/splatmoji" ]; then
  git clone https://github.com/cspeterson/splatmoji.git "${HOME}/.bin/splatmoji"
else
  git -C "${HOME}/.bin/splatmoji" pull
fi

###
# Config
###
# dunst
echo "::::Replace notify-osd with dunst..."
sudo apt-get remove notify-osd
sudo killall notify-osd || true
sudo apt-get install dunst
notify-send "dunst test" "Are we dunst yet?"

# x resources enable precompilation options on boot
echo '::::Alter gdm3 default Xsession to NOT skip over prepocessor directives...'
sudo sed -i 's/-nocpp //g' /etc/gdm3/Xsession
echo '::::Merge in Xresources now...'
xrdb -merge ~/.Xresources
