#!/usr/bin/env bash

set -e

###
# Repos
###
sudo apt-get update

###
# Install
###
# Normal packages
echo '::::Install tools and applets upon which the i3 config will rely...'
sudo apt-get install \
  adwaita-icon-theme-full \
  autorandr \
  blueman \
  dmenu \
  fonts-font-awesome \
  gajim \
  gpick \
  gsimplecal \
  i3blocks \
  i3lock \
  kitty \
  lastpass-cli \
  libimage-exiftool-perl \
  pasystray \
  pavucontrol \
  pcmanfm-qt \
  peek \
  qalc \
  rofi \
  scrot \
  ubuntu-restricted-extras \
  udiskie \
  vim-gtk3 \
  vlc \
  xautolock \
  xsel \


## Other
echo '::::Install from misc...'

# Vim-
if [ ! -d "${HOME}/.bin/vim-anywhere" ]; then
  git clone https://github.com/cspeterson/vim-anywhere.git "${HOME}/.bin/vim-anywhere"
else
  git -C "${HOME}/.bin/vim-anywhere" pull
fi

# emoji input via my splatmoji script
# https://github.com/cspeterson/splatmoji
echo '::::Install/update splatmoji...'
if ! [ -d "${HOME}/.bin/splatmoji.git" ]; then
  git clone https://github.com/cspeterson/splatmoji.git "${HOME}/.bin/splatmoji.git"
else
  git -C "${HOME}/.bin/splatmoji.git" pull || echo
fi
ln -s "${HOME}/.bin/splatmoji.git/splatmoji" "${HOME}/.bin/splatmoji" || true

if [ ! -f "${HOME}/.bin/find-cursor" ]; then
  rm -rf /tmp/find-cursor
  git clone https://github.com/arp242/find-cursor.git /tmp/find-cursor/
  (cd /tmp/find-cursor && make)
  cp /tmp/find-cursor/find-cursor "${HOME}/.bin/find-cursor"
  rm -rf /tmp/find-cursor/
fi

###
# Config
###
# dunst
echo "::::Replace notify-osd with dunst..."
sudo apt-get remove notify-osd
sudo killall notify-osd || true
sudo apt-get install dunst
notify-send "dunst test" "Are we dunst yet?"

# x resources enable precompilation options on boot
echo '::::Alter gdm3 default Xsession to NOT skip over prepocessor directives...'
sudo sed -i 's/-nocpp //g' /etc/gdm3/Xsession
echo '::::Merge in Xresources now...'
xrdb -merge ~/.Xresources
