#!/usr/bin/env bash
set -e

addon_path="${HOME}/.config/blender/2.79/scripts/addons"

echo 'Install blender plugins...'
mkdir -p "${addon_path}"

# Simple single-file downloads
wget -O "${addon_path}/vse-loop.py" 'https://raw.githubusercontent.com/mutantbob/blender-vse-loop/master/vse-loop.py'
wget -O "${addon_path}/VSE_Transform_Tool.py" 'https://raw.githubusercontent.com/kgeogeo/VSE_Transform_Tools/master/VSE_Transform_Tool.py'

# Blender Power sequencer
# https://github.com/GDquest/Blender-power-sequencer
wget -O /tmp/power-sequencer.zip 'https://github.com/GDquest/Blender-power-sequencer/releases/download/1.2.0/power-sequencer-1.2.zip'
unzip /tmp/power-sequencer.zip -d "${addon_path}"
chmod -R g-rwx "${addon_path}/power-sequencer/"
chmod -R o-rwx "${addon_path}/power-sequencer/"

# Real Time Animation
# https://sites.google.com/site/pointatstuffweb/
wget -O /tmp/realtimeanimation.zip 'https://sites.google.com/site/pointatstuffweb/real_time_animation_2_6.zip?attredirects=0&d=1'
unzip -j /tmp/realtimeanimation.zip real_time_animation_2_6/real_time_animation.py -d "${addon_path}"
