#!/usr/bin/env bash
set -e

echo "Installing audacity..."
sudo apt-get install audacity

plugins=(
  'http://wiki.audacityteam.org/w/images/7/75/Noisegate.ny'
  'https://raw.githubusercontent.com/theDanielJLewis/dynamic-compressor-for-audacity/master/compress.ny'
)

status=0

echo "Installing Audacity plugins if not installed..."
for plugin in ${plugins[@]}; do
	filename=$(basename "${plugin}")
	plugindir="${HOME}/.audacity-files/plug-ins"
	filepath="${plugindir}/${filename}"
  echo "Installing plugin ${filename}..."
  mkdir -p "${plugindir}"
  # If wget tries to download and fails, it will leave a zero-sized file. If
  # this is being run to try to update plugins and we run into a 404, that
  # would wipe out our plugins. Play safe:
  wget -O "${filepath}.tmp" "${plugin}" >/dev/null && \
    mv "${filepath}.tmp" "${filepath}" || \
    echo "Something went wrong with '${plugin}'! Could not mv temp file." && \
    status=1
done

exit $status
