#!/bin/sh

xrandr \
  --output GPU-1.DVI-I-2 \
    --off \
  --output GPU-1.DVI-I-3 \
    --off \

xrandr \
  --output GPU-0.DVI-I-2 \
    --mode 1920x1080 \
    --pos 0x160 \
    --rotate normal \
  --output GPU-0.DVI-I-3 \
    --primary \
    --mode 1920x1080 \
    --pos 1920x160 \
    --rotate normal \
  --output GPU-1.DVI-I-3 \
    --mode 1920x1080 \
    --pos 3840x-180 \
    --rotate left \
  --output GPU-1.DVI-I-2 \
    --mode 1920x1080 \
    --pos 4940x290 \
    --rotate left \

